### ISSUE TITLE
Installationsprobleme

### ISSUE THREAD

**Issue by serav993** [wiegehtki/zoneminder#1]
Ihr Projekt ist außerordentlich interessant, jedoch gestaltet sich die Installation etwas schwerer als in den Videos erklärt, zumindest mit neueren Versionen der CUdnn Bibliothek. Ich hatte schon in der Final.sh geschaut, welche Versionen dort angezeigt sind.
Mit CUDA 10.2 klappt es nicht.
Die Fehlermeldung im FinalInst.log

`Sun Feb 6 20:47:07 UTC 2022 Kompilieren der CUDA - Beispiele um DeviceQuery zu ermoeglichen
Sun Feb 6 20:47:18 UTC 2022 Fehler beim  Ausfuehren von deviceQuery! Standardwert fuer CUDA_COMPUTE_CAPABILITY wird beibehalten!`
Mit CUDA 10.1 kommt beim Training von Gesichtern folgende Meldung
`sudo: unable to execute /var/lib/zmeventnotification/bin/zm_train_faces.py: No such file or directory`

Bin im 2. Installationsversuch, sollte dieser scheitern, werde ich genau die Version, wie im Video zu sehen ist, nutzen.
Kann ich dazu auch die Final.sh starten oder die Final_old-sh?
Ich würde mich sehr über eine Antwort freuen, denn Ihr Projekt ist außerordentlich gut veranschaulicht und die dazugehörigen Videos vermitteln eine gute Grundlage in Sachen "KI". 

Nachtrag mit der Inital.sh und Final.sh stoppt die Installation immer mit dem oben genannten Fehler. Habe nahezu sämtliche CUDNN Bibliotheken die der Beschreibung entsprechen durch. Nach einem Zwischenversuch viel mir auf, dass auch wenn man die Initial.sh nutzt und dann die Final_old.sh startet mit einer CUDnn 10.2 Version, die Installation deutlich weiterläuft.
Lauffähig ist es noch nicht, aber es geht wohl voran.
Eventuell liegt es auch an meinen noch nicht ausreichenden Fähigkeiten in diesem Bereich.
Eine kleine Hilfestellung oder Feedback, eventuell auch von jemandem der das nutzt wäre sehr freundlich.
Auch ein Hinweis zu einem entsprechenden Forum wäre gut. Das Nvidia Forum hat zum Beispiel auch interessante Hinweise geliefert.
Update:
Bei Ubuntu 18.04 wurde vom Standarttreiber meine Asus GTX 1650 nicht erkannt.
Das erklärte mir bis dato aber noch nicht die Startprobleme des Gesichtsttrainings.
MfG

**Comment by wiegehtki** [comment]
Danke für das Feedback, das Problem wurde behoben, bei meiner Installation funktioniert das jetzt. Bitte mit aktuellem Github Repo testen. Auch habe ich die Beschreibungen erweitert.

**Comment by serav993** [comment]
Guten Abend und vielen Dank für Ihre Mühen.

Diese Woche habe ich wieder viel Zeit und kann mich der Sache annehmen.
Meinen sie mit minimal und max Version bei Desktop und Server jewals mit oder ohne entsprechende Kernel der Version.
Z.B ubuntu Server 20.04 ohne Kernel
    Ubuntu Server 20.04 mit hwe Kernel
 
Liebe Grüße

**Comment by wiegehtki** [comment]
Guten Morgen,

gerne geschehen :)

Wenn man die Installation startet, kann man auswählen ob minimal oder mit
vorinstallierten Apps. Ich habe hier die minimale Version getestet,
theoretisch müsste auch die andere laufen. Das prüfe ich aber noch.

Außerdem kann man 3rd Party Treiber aktivieren. Das solltet man NICHT
machen! Das Problem ist, dass zwar die Treiber incl. Cuda funktionieren
aber das ist kein Standard bei den Installationspfaden. Selbst die original
Nvidia Tools finden später die eigene Software nicht mehr und das will was
heißen.

Beim testen den Eintrag Cuda bei der Kamera erstmal weglassen und schauen,
ob die Erkennung geht.

Beste Grüße,
Udo Würtz


serav993 ***@***.***> schrieb am Di., 1. März 2022, 00:02:

**Comment by serav993** [comment]
Guten Abend,

wollte es soeben testen mit Ubuntu Desktop(minimal) und bekam nach Ausführen der Final.sh folgende Meldung.
Im ersten Installationsschritt wurde der Noeuvau-Treiber auch korrekt entfernt. Das hatte ich im Installationlog nachgeschaut und auch die Auflösung war dementsprechend schlecht nachm Neustart. 
Der Fehler kommt auch direkt nach dem Download von cuda_11.6. Kann es eventuell an meiner Hardware liegen ?

Meldung aus dem FinalInstalllog:

`Di 1. Mär 18:04:48 UTC 2022 CUDA - Download und Installation inklusive Grafiktreiber
  *-display UNGEFORDERT
       Beschreibung: VGA compatible controller
       Produkt: TU117 [GeForce GTX 1650]
       Hersteller: NVIDIA Corporation
       Physische ID: 0
       Bus-Informationen: pci@0000:01:00.0
       Version: a1
       Breite: 64 bits
       Takt: 33MHz
       Fähigkeiten: pm msi pciexpress vga_controller cap_list
       Konfiguration: latency=0
       Ressourcen: memory:a2000000-a2ffffff memory:90000000-9fffffff memory:a0000000-a1ffffff ioport:5000(Größe=128) memory:c0000-dffff
Di 1. Mär 18:10:58 UTC 2022 Kompilieren der CUDA - Beispiele um DeviceQuery zu ermoeglichen
Di 1. Mär 18:10:58 UTC 2022 Fehler beim  Ausfuehren von deviceQuery! Standardwert fuer CUDA_COMPUTE_CAPABILITY wird beibehalten!`

MfG
Serav

**Comment by wiegehtki** [comment]
Gute Frage. Ich würde morgen das Ganze mal mit meiner 1070 laufen lassen.
Aktuell habe ich die GV100 verwendet.

Ich melde mich morgen.

Beste Grüße,
Udo Würtz

serav993 ***@***.***> schrieb am Di., 1. März 2022, 19:21:

**Comment by serav993** [comment]
Danke für die Antwort.
Die genaue Bezeichnung der Grafikkarte lautet : 
ASUS GTX1650-O4G-LP-BRK

Ich werde es Ende der Woche nochmal mit einer anderen Nvidia Grafikkarte testen.

**Comment by wiegehtki** [comment]
Ist das Ubuntu 21.10 oder 20.04? Bei 20.04 läuft das bei mir sauber durch. Ich schaue mir gerade nochmal 21.10 an

**Comment by serav993** [comment]
Nutze Ubuntu 20.04 Server mit hwe Kernel.

**Comment by wiegehtki** [comment]
Teste ich, bin gerade dran

**Comment by serav993** [comment]
Guten Morgen, 
haben SIe eventuell schon etwas herausfinden Können ?
lG

**Comment by serav993** [comment]
Guten Abend,

habe es heute mal mit Ubuntu 20.04.4 minimal Desktop versucht und es klappt. Es gibt noch ein paar Errors etc aber die bekomme ich mit der Zeit ausgebügelt denke ich.
Vielen Dank für diese tolle Arbeit und hoffentlich wird noch weiter Zeit und Fleiß in dieses Projekt gesteckt
